### ISSUE TITLE
Support in-flight rate adjustment 

### ISSUE THREAD

**Issue by keirlawson** [SystemFw/upperbound#2]
It would be useful to be able to set the rate of the worker after the worker is initially created, to cover cases where the desired rate may change with application  logic and we want to apply any new rate to the existing queue

**Comment by SystemFw** [comment]
The underlying mechanism to do so is already there (it's used for back pressure), so it's just  a matter of deciding the best way to expose it.

**Comment by kiambogo** [comment]
@SystemFw did you have an opinion on how to design this? 

I think the easiest approach would be to remove the backoff parameter from the limiter and instead allowing that function to live on the BackPressure model. The worker can then create a no-op job with backoff set which will alter the rate of the limiter based on what the worker has requested. A helper method can exist on the worker in order to make the API more idiomatic:
```scala
w.adjustLimiterRate(100 every 1.minute)
```
Problem with this approach is that the internal naming is a bit of an oxymoron in the case that the rate increases. 

I need this for a project within my work, so I'd be happy to open a PR but want to discuss some designs first.

**Comment by SystemFw** [comment]
well, I think that just exposing the `Signal` (or the `Ref`, if I replace it) would be better than offering several helper methods. I kinda want to do a broader redesign before releasing for 1.0, but I keep getting side tracked by other work in fs2 proper or cats-effect

**Comment by SystemFw** [comment]
This is fixed in 0.2.0-M2
